// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/bigint.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BigInt is an arbitrary precision integer.
type BigInt struct {
	// Bytes are interpreted as a big-endian unsigned integer.
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Negative             bool     `protobuf:"varint,2,opt,name=negative,proto3" json:"negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_16edd3e168faa7de, []int{0}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *BigInt) GetNegative() bool {
	if m != nil {
		return m.Negative
	}
	return false
}

func init() {
	proto.RegisterType((*BigInt)(nil), "protos.BigInt")
}

func init() { proto.RegisterFile("protos/bigint.proto", fileDescriptor_16edd3e168faa7de) }

var fileDescriptor_16edd3e168faa7de = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0xca, 0x4c, 0xcf, 0xcc, 0x2b, 0xd1, 0x03, 0xf3, 0x84, 0xd8, 0x20, 0x82,
	0x4a, 0x56, 0x5c, 0x6c, 0x4e, 0x99, 0xe9, 0x9e, 0x79, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x49, 0x95,
	0x25, 0xa9, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10, 0x8e, 0x90, 0x14, 0x17, 0x47,
	0x5e, 0x6a, 0x7a, 0x62, 0x49, 0x66, 0x59, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x9c,
	0xef, 0xa4, 0x13, 0xa5, 0x95, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f,
	0x9b, 0x9a, 0x9e, 0x58, 0x5c, 0x90, 0x98, 0x9c, 0x9a, 0x93, 0x98, 0x04, 0xe6, 0x24, 0xe7, 0xe7,
	0xe5, 0xa5, 0x26, 0x97, 0xe8, 0x43, 0x6c, 0x4a, 0x82, 0xd8, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x0c, 0x33, 0xb6, 0x1f, 0x8f, 0x00, 0x00, 0x00,
}
