// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/block.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Block represents a block reported by a connected chain.
type Block struct {
	Chain                string   `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte   `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Height               *BigInt  `protobuf:"bytes,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b973894188f6a7, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *Block) GetHeight() *BigInt {
	if m != nil {
		return m.Height
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "protos.Block")
}

func init() { proto.RegisterFile("protos/block.proto", fileDescriptor_38b973894188f6a7) }

var fileDescriptor_38b973894188f6a7 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0xc9, 0xf7, 0xb5, 0x05, 0x53, 0x71, 0x88, 0x0e, 0xc5, 0xc5, 0xe2, 0x20, 0x45, 0xa4,
	0x05, 0xfd, 0x07, 0x9d, 0x74, 0xed, 0xe8, 0x22, 0x49, 0x08, 0x49, 0xb0, 0x4d, 0x4a, 0x73, 0x2e,
	0xfe, 0x7a, 0x69, 0x4e, 0xb7, 0x7b, 0xde, 0xe7, 0x3d, 0x8e, 0xa3, 0x6c, 0x9c, 0x3c, 0xf8, 0xd0,
	0x88, 0xde, 0xcb, 0x67, 0x1d, 0x81, 0x65, 0x98, 0x6d, 0xd7, 0x3f, 0x67, 0xb5, 0x75, 0x80, 0x72,
	0xff, 0xa6, 0x69, 0x3b, 0x77, 0xd9, 0x86, 0xa6, 0xd2, 0x70, 0xeb, 0x0a, 0x52, 0x92, 0x6a, 0xd1,
	0x21, 0x30, 0x46, 0x13, 0xc3, 0x83, 0x29, 0xfe, 0x4a, 0x52, 0x2d, 0xbb, 0x38, 0xb3, 0x1d, 0xcd,
	0x47, 0x3e, 0x29, 0x07, 0x8f, 0xa8, 0xfe, 0xa3, 0xa2, 0x18, 0x5d, 0xe7, 0xc2, 0x81, 0x66, 0x46,
	0x59, 0x6d, 0xa0, 0x48, 0x4a, 0x52, 0xe5, 0xe7, 0x15, 0xde, 0x0a, 0x75, 0x6b, 0xf5, 0xcd, 0x41,
	0xf7, 0xb5, 0xed, 0xe9, 0x7e, 0xd4, 0x16, 0xcc, 0x4b, 0xd4, 0xd2, 0x0f, 0xcd, 0xa0, 0x34, 0x0f,
	0x23, 0x97, 0xaa, 0xe7, 0x22, 0x82, 0xf4, 0xce, 0x29, 0x09, 0x0d, 0x2e, 0x0b, 0x7c, 0xe3, 0xf2,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xef, 0x22, 0x7e, 0x11, 0xe3, 0x00, 0x00, 0x00,
}
