// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/event.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MonitorEvent is an event fired by a monitor.
type MonitorEvent struct {
	WorkflowId           []byte   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	MonitorName          string   `protobuf:"bytes,2,opt,name=monitor_name,json=monitorName,proto3" json:"monitor_name,omitempty"`
	EventName            string   `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorEvent) Reset()         { *m = MonitorEvent{} }
func (m *MonitorEvent) String() string { return proto.CompactTextString(m) }
func (*MonitorEvent) ProtoMessage()    {}
func (*MonitorEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec55cd27928da5d, []int{0}
}

func (m *MonitorEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorEvent.Unmarshal(m, b)
}
func (m *MonitorEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorEvent.Marshal(b, m, deterministic)
}
func (m *MonitorEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorEvent.Merge(m, src)
}
func (m *MonitorEvent) XXX_Size() int {
	return xxx_messageInfo_MonitorEvent.Size(m)
}
func (m *MonitorEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorEvent proto.InternalMessageInfo

func (m *MonitorEvent) GetWorkflowId() []byte {
	if m != nil {
		return m.WorkflowId
	}
	return nil
}

func (m *MonitorEvent) GetMonitorName() string {
	if m != nil {
		return m.MonitorName
	}
	return ""
}

func (m *MonitorEvent) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *MonitorEvent) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// ActionEvent is an event fired by an action.
type ActionEvent struct {
	WorkflowId           []byte   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ActionName           string   `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	EventName            string   `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionEvent) Reset()         { *m = ActionEvent{} }
func (m *ActionEvent) String() string { return proto.CompactTextString(m) }
func (*ActionEvent) ProtoMessage()    {}
func (*ActionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec55cd27928da5d, []int{1}
}

func (m *ActionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionEvent.Unmarshal(m, b)
}
func (m *ActionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionEvent.Marshal(b, m, deterministic)
}
func (m *ActionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionEvent.Merge(m, src)
}
func (m *ActionEvent) XXX_Size() int {
	return xxx_messageInfo_ActionEvent.Size(m)
}
func (m *ActionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ActionEvent proto.InternalMessageInfo

func (m *ActionEvent) GetWorkflowId() []byte {
	if m != nil {
		return m.WorkflowId
	}
	return nil
}

func (m *ActionEvent) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *ActionEvent) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *ActionEvent) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*MonitorEvent)(nil), "protos.MonitorEvent")
	proto.RegisterType((*ActionEvent)(nil), "protos.ActionEvent")
}

func init() { proto.RegisterFile("protos/event.proto", fileDescriptor_bec55cd27928da5d) }

var fileDescriptor_bec55cd27928da5d = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0xd1, 0x03, 0x73, 0x84, 0xd8, 0x20, 0x62, 0x4a,
	0xdd, 0x8c, 0x5c, 0x3c, 0xbe, 0xf9, 0x79, 0x99, 0x25, 0xf9, 0x45, 0xae, 0x20, 0x69, 0x21, 0x79,
	0x2e, 0xee, 0xf2, 0xfc, 0xa2, 0xec, 0xb4, 0x9c, 0xfc, 0xf2, 0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x2e, 0x98, 0x90, 0x67, 0x8a, 0x90, 0x22, 0x17, 0x4f, 0x2e, 0x44, 0x43,
	0x7c, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x37, 0x54, 0xcc, 0x2f,
	0x31, 0x37, 0x55, 0x48, 0x96, 0x8b, 0x0b, 0x6c, 0x17, 0x44, 0x01, 0x33, 0x58, 0x01, 0x27, 0x58,
	0x04, 0x2c, 0x2d, 0xc1, 0xc5, 0x5e, 0x90, 0x58, 0x99, 0x93, 0x9f, 0x98, 0x22, 0xc1, 0x02, 0x36,
	0x1e, 0xc6, 0x55, 0xea, 0x60, 0xe4, 0xe2, 0x76, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x23, 0xd2, 0x31,
	0xf2, 0x5c, 0xdc, 0x89, 0x60, 0xf5, 0xc8, 0x6e, 0xe1, 0x82, 0x08, 0x51, 0xe4, 0x14, 0x27, 0x9d,
	0x28, 0xad, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xdc, 0xd4, 0xf4,
	0xc4, 0xe2, 0x82, 0xc4, 0xe4, 0xd4, 0x9c, 0xc4, 0x24, 0x30, 0x27, 0x39, 0x3f, 0x2f, 0x2f, 0x35,
	0xb9, 0x44, 0x1f, 0x12, 0x8c, 0x49, 0x90, 0xe0, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0x9c, 0xde, 0x72, 0x6b, 0x01, 0x00, 0x00,
}
