// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/mblock.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MBlock represents a Megaspace block to be agreed upon among consensus nodes.
type MBlock struct {
	Height               int64     `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash                 []byte    `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte    `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Events               []*MEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MBlock) Reset()         { *m = MBlock{} }
func (m *MBlock) String() string { return proto.CompactTextString(m) }
func (*MBlock) ProtoMessage()    {}
func (*MBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_19f6a7ee678aa0e0, []int{0}
}

func (m *MBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MBlock.Unmarshal(m, b)
}
func (m *MBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MBlock.Marshal(b, m, deterministic)
}
func (m *MBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MBlock.Merge(m, src)
}
func (m *MBlock) XXX_Size() int {
	return xxx_messageInfo_MBlock.Size(m)
}
func (m *MBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MBlock proto.InternalMessageInfo

func (m *MBlock) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *MBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MBlock) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *MBlock) GetEvents() []*MEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*MBlock)(nil), "protos.MBlock")
}

func init() { proto.RegisterFile("protos/mblock.proto", fileDescriptor_19f6a7ee678aa0e0) }

var fileDescriptor_19f6a7ee678aa0e0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x4d, 0xca, 0xc9, 0x4f, 0xce, 0xd6, 0x03, 0xf3, 0x84, 0xd8, 0x20, 0x82,
	0x52, 0x70, 0xc9, 0xd4, 0xb2, 0xd4, 0xbc, 0x12, 0x88, 0xa4, 0x52, 0x2d, 0x17, 0x9b, 0xaf, 0x13,
	0x48, 0xb1, 0x90, 0x18, 0x17, 0x5b, 0x46, 0x6a, 0x66, 0x7a, 0x46, 0x89, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x73, 0x10, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x92, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x13, 0x04, 0x66, 0x0b, 0xc9, 0x73, 0x71, 0x17, 0x24, 0x16, 0xa5, 0xe6, 0x95, 0xc4,
	0x83, 0xa5, 0x98, 0xc1, 0x52, 0x5c, 0x10, 0x21, 0x0f, 0x90, 0x02, 0x35, 0x2e, 0x36, 0xb0, 0x2d,
	0xc5, 0x12, 0x2c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x7c, 0x10, 0xeb, 0x8a, 0xf5, 0x7c, 0x5d, 0x41,
	0xc2, 0x41, 0x50, 0x59, 0x27, 0x9d, 0x28, 0xad, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4,
	0xfc, 0x5c, 0xfd, 0xdc, 0xd4, 0xf4, 0xc4, 0xe2, 0x82, 0xc4, 0xe4, 0xd4, 0x9c, 0xc4, 0x24, 0x30,
	0x27, 0x39, 0x3f, 0x2f, 0x2f, 0x35, 0xb9, 0x44, 0x1f, 0xa2, 0x39, 0x09, 0xe2, 0x13, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x84, 0xef, 0xca, 0xe7, 0x00, 0x00, 0x00,
}
