// Code generated by gocc; DO NOT EDIT.

package parser

import (
    pa "github.com/megaspacelab/megaconnect/workflow/parser/utils"
    wf "github.com/megaspacelab/megaconnect/workflow"    
    "github.com/megaspacelab/megaconnect/workflow/parser/goccgen/token"
)

type (
	//TODO: change type and variable names to be consistent with other tables
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Workflow	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Workflow : kdWorkflow id "{" Decls "}"	<< wf.NewWorkflowDecl(pa.Lit(X[1]), 0).AddChildren(X[3].([]wf.Decl)), nil >>`,
		Id:         "Workflow",
		NTType:     1,
		Index:      1,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewWorkflowDecl(pa.Lit(X[1]), 0).AddChildren(X[3].([]wf.Decl)), nil
		},
	},
	ProdTabEntry{
		String: `Decls : Decl	<< []wf.Decl{X[0].(wf.Decl)}, nil >>`,
		Id:         "Decls",
		NTType:     2,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return []wf.Decl{X[0].(wf.Decl)}, nil
		},
	},
	ProdTabEntry{
		String: `Decls : Decls Decl	<< append(X[0].([]wf.Decl), X[1].([]wf.Decl)[0]), nil >>`,
		Id:         "Decls",
		NTType:     2,
		Index:      3,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return append(X[0].([]wf.Decl), X[1].([]wf.Decl)[0]), nil
		},
	},
	ProdTabEntry{
		String: `Decl : Monitor	<<  >>`,
		Id:         "Decl",
		NTType:     3,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Decl : empty	<<  >>`,
		Id:         "Decl",
		NTType:     3,
		Index:      5,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Monitor : kdMonitor id kdChain id kdCondition Expr MonitorVar kdFire id ObjLit	<< pa.MonitorAction(X[1], X[3], X[5], X[6], X[8], X[9]) >>`,
		Id:         "Monitor",
		NTType:     4,
		Index:      6,
		NumSymbols: 10,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.MonitorAction(X[1], X[3], X[5], X[6], X[8], X[9])
		},
	},
	ProdTabEntry{
		String: `MonitorVar : kdVar "{" VarDecls "}"	<< X[2], nil >>`,
		Id:         "MonitorVar",
		NTType:     5,
		Index:      7,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[2], nil
		},
	},
	ProdTabEntry{
		String: `MonitorVar : empty	<<  >>`,
		Id:         "MonitorVar",
		NTType:     5,
		Index:      8,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ObjLit : "{" ObjLitFields "}"	<< X[1], nil >>`,
		Id:         "ObjLit",
		NTType:     6,
		Index:      9,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String: `ObjLitField : id ":" Expr ","	<< pa.VarDeclAction(X[0], X[2]) >>`,
		Id:         "ObjLitField",
		NTType:     7,
		Index:      10,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.VarDeclAction(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `ObjLitField : empty	<<  >>`,
		Id:         "ObjLitField",
		NTType:     7,
		Index:      11,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ObjLitFields : ObjLitField	<<  >>`,
		Id:         "ObjLitFields",
		NTType:     8,
		Index:      12,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ObjLitFields : ObjLitFields ObjLitField	<< pa.VarDeclsAction(X[0], X[1]) >>`,
		Id:         "ObjLitFields",
		NTType:     8,
		Index:      13,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.VarDeclsAction(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `VarDecl : id "=" Expr	<< pa.VarDeclAction(X[0], X[2]) >>`,
		Id:         "VarDecl",
		NTType:     9,
		Index:      14,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.VarDeclAction(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `VarDecl : empty	<<  >>`,
		Id:         "VarDecl",
		NTType:     9,
		Index:      15,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `VarDecls : VarDecl	<<  >>`,
		Id:         "VarDecls",
		NTType:     10,
		Index:      16,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VarDecls : VarDecls VarDecl	<< pa.VarDeclsAction(X[0], X[1]) >>`,
		Id:         "VarDecls",
		NTType:     10,
		Index:      17,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.VarDeclsAction(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `MonitorProperty : kdChain ":" id	<<  >>`,
		Id:         "MonitorProperty",
		NTType:     11,
		Index:      18,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MonitorProperty : kdCondition ":" Expr	<<  >>`,
		Id:         "MonitorProperty",
		NTType:     11,
		Index:      19,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MonitorProperties : MonitorProperty	<<  >>`,
		Id:         "MonitorProperties",
		NTType:     12,
		Index:      20,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MonitorProperties : MonitorProperty MonitorProperties	<<  >>`,
		Id:         "MonitorProperties",
		NTType:     12,
		Index:      21,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Expr : Expr "||" Term1	<< wf.NewBinOp(wf.OrOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Expr",
		NTType:     13,
		Index:      22,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.OrOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Expr : Expr "&&" Term1	<< wf.NewBinOp(wf.AndOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Expr",
		NTType:     13,
		Index:      23,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.AndOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Expr : Term1	<<  >>`,
		Id:         "Expr",
		NTType:     13,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term1 "==" Term2	<< wf.NewBinOp(wf.EqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      25,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.EqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term1 "!=" Term2	<< wf.NewBinOp(wf.NotEqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      26,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.NotEqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term1 ">" Term2	<< wf.NewBinOp(wf.GreaterThanOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      27,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.GreaterThanOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term1 ">=" Term2	<< wf.NewBinOp(wf.GreaterThanEqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      28,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.GreaterThanEqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term1 "<" Term2	<< wf.NewBinOp(wf.LessThanOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      29,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.LessThanOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term1 "<=" Term2	<< wf.NewBinOp(wf.LessThanEqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      30,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.LessThanEqualOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term1 : Term2	<<  >>`,
		Id:         "Term1",
		NTType:     14,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term2 : Term2 "+" Term3	<< wf.NewBinOp(wf.PlusOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term2",
		NTType:     15,
		Index:      32,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.PlusOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term2 : Term2 "-" Term3	<< wf.NewBinOp(wf.MinusOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term2",
		NTType:     15,
		Index:      33,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.MinusOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term2 : Term3	<<  >>`,
		Id:         "Term2",
		NTType:     15,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term3 : Term3 "*" Term4	<< wf.NewBinOp(wf.MultOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term3",
		NTType:     16,
		Index:      35,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.MultOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term3 : Term3 "/" Term4	<< wf.NewBinOp(wf.DivOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil >>`,
		Id:         "Term3",
		NTType:     16,
		Index:      36,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewBinOp(wf.DivOp, X[0].(wf.Expr), X[2].(wf.Expr)), nil
		},
	},
	ProdTabEntry{
		String: `Term3 : Term4	<<  >>`,
		Id:         "Term3",
		NTType:     16,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term4 : boolLit	<< pa.BoolLitAction(X[0]) >>`,
		Id:         "Term4",
		NTType:     17,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.BoolLitAction(X[0])
		},
	},
	ProdTabEntry{
		String: `Term4 : stringLit	<< pa.StrLitAction(X[0]) >>`,
		Id:         "Term4",
		NTType:     17,
		Index:      39,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return pa.StrLitAction(X[0])
		},
	},
	ProdTabEntry{
		String: `Term4 : id	<< wf.NewVar(string(X[0].(*token.Token).Lit)), nil >>`,
		Id:         "Term4",
		NTType:     17,
		Index:      40,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return wf.NewVar(string(X[0].(*token.Token).Lit)), nil
		},
	},
	ProdTabEntry{
		String: `Term4 : "(" Expr ")"	<< X[1], nil >>`,
		Id:         "Term4",
		NTType:     17,
		Index:      41,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[1], nil
		},
	},
}
