// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orchestrator.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterChainManagerRequest struct {
	// ChainManagerId identifies the instance of the requesting ChainManager.
	ChainManagerId *InstanceId `protobuf:"bytes,1,opt,name=chain_manager_id,json=chainManagerId,proto3" json:"chain_manager_id,omitempty"`
	// ChainId identifies the chain being managed.
	ChainId string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// ListenPort allows Orchestrator to reach out to this ChainManager.
	ListenPort int32 `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// SessionId should be included in all outbound communications from Orchestrator to ChainManager as a validity proof.
	SessionId            []byte   `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterChainManagerRequest) Reset()         { *m = RegisterChainManagerRequest{} }
func (m *RegisterChainManagerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterChainManagerRequest) ProtoMessage()    {}
func (*RegisterChainManagerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{0}
}

func (m *RegisterChainManagerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterChainManagerRequest.Unmarshal(m, b)
}
func (m *RegisterChainManagerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterChainManagerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterChainManagerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterChainManagerRequest.Merge(m, src)
}
func (m *RegisterChainManagerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterChainManagerRequest.Size(m)
}
func (m *RegisterChainManagerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterChainManagerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterChainManagerRequest proto.InternalMessageInfo

func (m *RegisterChainManagerRequest) GetChainManagerId() *InstanceId {
	if m != nil {
		return m.ChainManagerId
	}
	return nil
}

func (m *RegisterChainManagerRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *RegisterChainManagerRequest) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func (m *RegisterChainManagerRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type RegisterChainManagerResponse struct {
	// Lease indicates the validity period allocated to the requesting ChainManager.
	Lease *Lease `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	// ResumeAfter indicates the last processed block by Orchestrator.
	// If not nil, ChainManager is expected to start reporting from right after this block.
	// Otherwise, ChainManager can start reporting from the next new block.
	ResumeAfter *BlockSpec `protobuf:"bytes,2,opt,name=resume_after,json=resumeAfter,proto3" json:"resume_after,omitempty"`
	// Monitors contain all things to be monitored by the requesting ChainManager.
	Monitors             *MonitorSet `protobuf:"bytes,3,opt,name=monitors,proto3" json:"monitors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterChainManagerResponse) Reset()         { *m = RegisterChainManagerResponse{} }
func (m *RegisterChainManagerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterChainManagerResponse) ProtoMessage()    {}
func (*RegisterChainManagerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{1}
}

func (m *RegisterChainManagerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterChainManagerResponse.Unmarshal(m, b)
}
func (m *RegisterChainManagerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterChainManagerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterChainManagerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterChainManagerResponse.Merge(m, src)
}
func (m *RegisterChainManagerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterChainManagerResponse.Size(m)
}
func (m *RegisterChainManagerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterChainManagerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterChainManagerResponse proto.InternalMessageInfo

func (m *RegisterChainManagerResponse) GetLease() *Lease {
	if m != nil {
		return m.Lease
	}
	return nil
}

func (m *RegisterChainManagerResponse) GetResumeAfter() *BlockSpec {
	if m != nil {
		return m.ResumeAfter
	}
	return nil
}

func (m *RegisterChainManagerResponse) GetMonitors() *MonitorSet {
	if m != nil {
		return m.Monitors
	}
	return nil
}

type UnregisterChainManagerRequest struct {
	// ChainId identifies the chain being managed.
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// LeaseId must be the id of a still valid Lease of to be unregistered chain manager.
	LeaseId []byte `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// Message indicates the reason of the unregistration.
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterChainManagerRequest) Reset()         { *m = UnregisterChainManagerRequest{} }
func (m *UnregisterChainManagerRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterChainManagerRequest) ProtoMessage()    {}
func (*UnregisterChainManagerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{2}
}

func (m *UnregisterChainManagerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterChainManagerRequest.Unmarshal(m, b)
}
func (m *UnregisterChainManagerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterChainManagerRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterChainManagerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterChainManagerRequest.Merge(m, src)
}
func (m *UnregisterChainManagerRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterChainManagerRequest.Size(m)
}
func (m *UnregisterChainManagerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterChainManagerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterChainManagerRequest proto.InternalMessageInfo

func (m *UnregisterChainManagerRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *UnregisterChainManagerRequest) GetLeaseId() []byte {
	if m != nil {
		return m.LeaseId
	}
	return nil
}

func (m *UnregisterChainManagerRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// InstanceId identifies a specific instance of an entity.
type InstanceId struct {
	// Id is the entity id.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Instance is a monotonically increasing sequence number, namespaced by Id.
	Instance             uint32   `protobuf:"varint,2,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceId) Reset()         { *m = InstanceId{} }
func (m *InstanceId) String() string { return proto.CompactTextString(m) }
func (*InstanceId) ProtoMessage()    {}
func (*InstanceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{3}
}

func (m *InstanceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceId.Unmarshal(m, b)
}
func (m *InstanceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceId.Marshal(b, m, deterministic)
}
func (m *InstanceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceId.Merge(m, src)
}
func (m *InstanceId) XXX_Size() int {
	return xxx_messageInfo_InstanceId.Size(m)
}
func (m *InstanceId) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceId.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceId proto.InternalMessageInfo

func (m *InstanceId) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *InstanceId) GetInstance() uint32 {
	if m != nil {
		return m.Instance
	}
	return 0
}

// BlockSpec is used to specify a block to be looked up.
// While Hash is the most accurate specification, when not available, Height can be used instead.
type BlockSpec struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               *BigInt  `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSpec) Reset()         { *m = BlockSpec{} }
func (m *BlockSpec) String() string { return proto.CompactTextString(m) }
func (*BlockSpec) ProtoMessage()    {}
func (*BlockSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{4}
}

func (m *BlockSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSpec.Unmarshal(m, b)
}
func (m *BlockSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSpec.Marshal(b, m, deterministic)
}
func (m *BlockSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSpec.Merge(m, src)
}
func (m *BlockSpec) XXX_Size() int {
	return xxx_messageInfo_BlockSpec.Size(m)
}
func (m *BlockSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSpec proto.InternalMessageInfo

func (m *BlockSpec) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockSpec) GetHeight() *BigInt {
	if m != nil {
		return m.Height
	}
	return nil
}

type MonitorSet struct {
	// Monitors contain all things to be monitored by the requesting ChainManager.
	Monitors []*Monitor `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	// Version is used for Orchestrator and ChainManager to agree on the set of monitors evaluated on each block.
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorSet) Reset()         { *m = MonitorSet{} }
func (m *MonitorSet) String() string { return proto.CompactTextString(m) }
func (*MonitorSet) ProtoMessage()    {}
func (*MonitorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{5}
}

func (m *MonitorSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorSet.Unmarshal(m, b)
}
func (m *MonitorSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorSet.Marshal(b, m, deterministic)
}
func (m *MonitorSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorSet.Merge(m, src)
}
func (m *MonitorSet) XXX_Size() int {
	return xxx_messageInfo_MonitorSet.Size(m)
}
func (m *MonitorSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorSet.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorSet proto.InternalMessageInfo

func (m *MonitorSet) GetMonitors() []*Monitor {
	if m != nil {
		return m.Monitors
	}
	return nil
}

func (m *MonitorSet) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// Monitor contains a list of encoded workflow expressions and a triggering condition
type Monitor struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// evaluations is a list of encoded workflow expressions, which will be evaluated if a monitor is triggered
	// the result will be passed back to flow manager as part of event. These expression results are intended for
	// evaluating actions
	Monitor              []byte   `protobuf:"bytes,2,opt,name=monitor,proto3" json:"monitor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Monitor) Reset()         { *m = Monitor{} }
func (m *Monitor) String() string { return proto.CompactTextString(m) }
func (*Monitor) ProtoMessage()    {}
func (*Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{6}
}

func (m *Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Monitor.Unmarshal(m, b)
}
func (m *Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Monitor.Marshal(b, m, deterministic)
}
func (m *Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Monitor.Merge(m, src)
}
func (m *Monitor) XXX_Size() int {
	return xxx_messageInfo_Monitor.Size(m)
}
func (m *Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_Monitor proto.InternalMessageInfo

func (m *Monitor) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Monitor) GetMonitor() []byte {
	if m != nil {
		return m.Monitor
	}
	return nil
}

type RenewLeaseRequest struct {
	// LeaseId must be the id of a still valid Lease.
	LeaseId              []byte   `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewLeaseRequest) Reset()         { *m = RenewLeaseRequest{} }
func (m *RenewLeaseRequest) String() string { return proto.CompactTextString(m) }
func (*RenewLeaseRequest) ProtoMessage()    {}
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{7}
}

func (m *RenewLeaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewLeaseRequest.Unmarshal(m, b)
}
func (m *RenewLeaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewLeaseRequest.Marshal(b, m, deterministic)
}
func (m *RenewLeaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewLeaseRequest.Merge(m, src)
}
func (m *RenewLeaseRequest) XXX_Size() int {
	return xxx_messageInfo_RenewLeaseRequest.Size(m)
}
func (m *RenewLeaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewLeaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenewLeaseRequest proto.InternalMessageInfo

func (m *RenewLeaseRequest) GetLeaseId() []byte {
	if m != nil {
		return m.LeaseId
	}
	return nil
}

type Lease struct {
	// Id uniquely identifies this Lease.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// RemainingSeconds indicates the length of the validity period in seconds.
	RemainingSeconds     uint32   `protobuf:"varint,2,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lease) Reset()         { *m = Lease{} }
func (m *Lease) String() string { return proto.CompactTextString(m) }
func (*Lease) ProtoMessage()    {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{8}
}

func (m *Lease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lease.Unmarshal(m, b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return xxx_messageInfo_Lease.Size(m)
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Lease) GetRemainingSeconds() uint32 {
	if m != nil {
		return m.RemainingSeconds
	}
	return 0
}

type ReportBlockEventsRequest struct {
	// Types that are valid to be assigned to MsgType:
	//	*ReportBlockEventsRequest_Preflight_
	//	*ReportBlockEventsRequest_Block
	//	*ReportBlockEventsRequest_Event
	MsgType              isReportBlockEventsRequest_MsgType `protobuf_oneof:"msg_type"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ReportBlockEventsRequest) Reset()         { *m = ReportBlockEventsRequest{} }
func (m *ReportBlockEventsRequest) String() string { return proto.CompactTextString(m) }
func (*ReportBlockEventsRequest) ProtoMessage()    {}
func (*ReportBlockEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{9}
}

func (m *ReportBlockEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportBlockEventsRequest.Unmarshal(m, b)
}
func (m *ReportBlockEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportBlockEventsRequest.Marshal(b, m, deterministic)
}
func (m *ReportBlockEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportBlockEventsRequest.Merge(m, src)
}
func (m *ReportBlockEventsRequest) XXX_Size() int {
	return xxx_messageInfo_ReportBlockEventsRequest.Size(m)
}
func (m *ReportBlockEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportBlockEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportBlockEventsRequest proto.InternalMessageInfo

type isReportBlockEventsRequest_MsgType interface {
	isReportBlockEventsRequest_MsgType()
}

type ReportBlockEventsRequest_Preflight_ struct {
	Preflight *ReportBlockEventsRequest_Preflight `protobuf:"bytes,1,opt,name=preflight,proto3,oneof"`
}

type ReportBlockEventsRequest_Block struct {
	Block *Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

type ReportBlockEventsRequest_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*ReportBlockEventsRequest_Preflight_) isReportBlockEventsRequest_MsgType() {}

func (*ReportBlockEventsRequest_Block) isReportBlockEventsRequest_MsgType() {}

func (*ReportBlockEventsRequest_Event) isReportBlockEventsRequest_MsgType() {}

func (m *ReportBlockEventsRequest) GetMsgType() isReportBlockEventsRequest_MsgType {
	if m != nil {
		return m.MsgType
	}
	return nil
}

func (m *ReportBlockEventsRequest) GetPreflight() *ReportBlockEventsRequest_Preflight {
	if x, ok := m.GetMsgType().(*ReportBlockEventsRequest_Preflight_); ok {
		return x.Preflight
	}
	return nil
}

func (m *ReportBlockEventsRequest) GetBlock() *Block {
	if x, ok := m.GetMsgType().(*ReportBlockEventsRequest_Block); ok {
		return x.Block
	}
	return nil
}

func (m *ReportBlockEventsRequest) GetEvent() *Event {
	if x, ok := m.GetMsgType().(*ReportBlockEventsRequest_Event); ok {
		return x.Event
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReportBlockEventsRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReportBlockEventsRequest_OneofMarshaler, _ReportBlockEventsRequest_OneofUnmarshaler, _ReportBlockEventsRequest_OneofSizer, []interface{}{
		(*ReportBlockEventsRequest_Preflight_)(nil),
		(*ReportBlockEventsRequest_Block)(nil),
		(*ReportBlockEventsRequest_Event)(nil),
	}
}

func _ReportBlockEventsRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReportBlockEventsRequest)
	// msg_type
	switch x := m.MsgType.(type) {
	case *ReportBlockEventsRequest_Preflight_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Preflight); err != nil {
			return err
		}
	case *ReportBlockEventsRequest_Block:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Block); err != nil {
			return err
		}
	case *ReportBlockEventsRequest_Event:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Event); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReportBlockEventsRequest.MsgType has unexpected type %T", x)
	}
	return nil
}

func _ReportBlockEventsRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReportBlockEventsRequest)
	switch tag {
	case 1: // msg_type.preflight
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReportBlockEventsRequest_Preflight)
		err := b.DecodeMessage(msg)
		m.MsgType = &ReportBlockEventsRequest_Preflight_{msg}
		return true, err
	case 2: // msg_type.block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Block)
		err := b.DecodeMessage(msg)
		m.MsgType = &ReportBlockEventsRequest_Block{msg}
		return true, err
	case 3: // msg_type.event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Event)
		err := b.DecodeMessage(msg)
		m.MsgType = &ReportBlockEventsRequest_Event{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReportBlockEventsRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReportBlockEventsRequest)
	// msg_type
	switch x := m.MsgType.(type) {
	case *ReportBlockEventsRequest_Preflight_:
		s := proto.Size(x.Preflight)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReportBlockEventsRequest_Block:
		s := proto.Size(x.Block)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReportBlockEventsRequest_Event:
		s := proto.Size(x.Event)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ReportBlockEventsRequest_Preflight struct {
	// LeaseId must be the id of a still valid Lease.
	LeaseId []byte `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// MonitorSetVersion is the version of the MonitorSet this block was processed with.
	MonitorSetVersion    uint32   `protobuf:"varint,2,opt,name=monitor_set_version,json=monitorSetVersion,proto3" json:"monitor_set_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportBlockEventsRequest_Preflight) Reset()         { *m = ReportBlockEventsRequest_Preflight{} }
func (m *ReportBlockEventsRequest_Preflight) String() string { return proto.CompactTextString(m) }
func (*ReportBlockEventsRequest_Preflight) ProtoMessage()    {}
func (*ReportBlockEventsRequest_Preflight) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{9, 0}
}

func (m *ReportBlockEventsRequest_Preflight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportBlockEventsRequest_Preflight.Unmarshal(m, b)
}
func (m *ReportBlockEventsRequest_Preflight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportBlockEventsRequest_Preflight.Marshal(b, m, deterministic)
}
func (m *ReportBlockEventsRequest_Preflight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportBlockEventsRequest_Preflight.Merge(m, src)
}
func (m *ReportBlockEventsRequest_Preflight) XXX_Size() int {
	return xxx_messageInfo_ReportBlockEventsRequest_Preflight.Size(m)
}
func (m *ReportBlockEventsRequest_Preflight) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportBlockEventsRequest_Preflight.DiscardUnknown(m)
}

var xxx_messageInfo_ReportBlockEventsRequest_Preflight proto.InternalMessageInfo

func (m *ReportBlockEventsRequest_Preflight) GetLeaseId() []byte {
	if m != nil {
		return m.LeaseId
	}
	return nil
}

func (m *ReportBlockEventsRequest_Preflight) GetMonitorSetVersion() uint32 {
	if m != nil {
		return m.MonitorSetVersion
	}
	return 0
}

// TODO - TBD
type Block struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte   `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Height               *BigInt  `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{10}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *Block) GetHeight() *BigInt {
	if m != nil {
		return m.Height
	}
	return nil
}

type BigInt struct {
	// Bytes are interpreted as a big-endian unsigned integer.
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Negative             bool     `protobuf:"varint,2,opt,name=negative,proto3" json:"negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{11}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *BigInt) GetNegative() bool {
	if m != nil {
		return m.Negative
	}
	return false
}

// Event describes a fired Monitor.
type Event struct {
	// MonitorId identifies the Monitor being fired.
	MonitorId []byte `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	// Event payload object encoded by workflow encoder
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_96b6e6782baaa298, []int{12}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetMonitorId() []byte {
	if m != nil {
		return m.MonitorId
	}
	return nil
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterChainManagerRequest)(nil), "grpc.RegisterChainManagerRequest")
	proto.RegisterType((*RegisterChainManagerResponse)(nil), "grpc.RegisterChainManagerResponse")
	proto.RegisterType((*UnregisterChainManagerRequest)(nil), "grpc.UnregisterChainManagerRequest")
	proto.RegisterType((*InstanceId)(nil), "grpc.InstanceId")
	proto.RegisterType((*BlockSpec)(nil), "grpc.BlockSpec")
	proto.RegisterType((*MonitorSet)(nil), "grpc.MonitorSet")
	proto.RegisterType((*Monitor)(nil), "grpc.Monitor")
	proto.RegisterType((*RenewLeaseRequest)(nil), "grpc.RenewLeaseRequest")
	proto.RegisterType((*Lease)(nil), "grpc.Lease")
	proto.RegisterType((*ReportBlockEventsRequest)(nil), "grpc.ReportBlockEventsRequest")
	proto.RegisterType((*ReportBlockEventsRequest_Preflight)(nil), "grpc.ReportBlockEventsRequest.Preflight")
	proto.RegisterType((*Block)(nil), "grpc.Block")
	proto.RegisterType((*BigInt)(nil), "grpc.BigInt")
	proto.RegisterType((*Event)(nil), "grpc.Event")
}

func init() { proto.RegisterFile("orchestrator.proto", fileDescriptor_96b6e6782baaa298) }

var fileDescriptor_96b6e6782baaa298 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xdd, 0x4e, 0xf3, 0x46,
	0x10, 0xfd, 0x1c, 0x08, 0x49, 0xc6, 0xf9, 0xbe, 0xc2, 0x16, 0xd1, 0x10, 0x4a, 0x09, 0xa6, 0x17,
	0xa9, 0x5a, 0x19, 0x29, 0xdc, 0x54, 0x5c, 0xb5, 0xb4, 0x48, 0x89, 0x54, 0x54, 0xba, 0x08, 0xee,
	0x2a, 0xcb, 0xb1, 0x07, 0xc7, 0x6a, 0xbc, 0xeb, 0xee, 0x2e, 0x54, 0x79, 0x8d, 0xbe, 0x42, 0x5f,
	0xa1, 0xef, 0xd0, 0xd7, 0xaa, 0xf6, 0xc7, 0x4e, 0xc2, 0x4f, 0xee, 0x3c, 0x67, 0xce, 0xee, 0x9e,
	0x3d, 0x33, 0x3b, 0x06, 0xc2, 0x45, 0x32, 0x43, 0xa9, 0x44, 0xac, 0xb8, 0x08, 0x4b, 0xc1, 0x15,
	0x27, 0xdb, 0x99, 0x28, 0x93, 0xfe, 0x51, 0xc6, 0x79, 0x36, 0xc7, 0x73, 0x83, 0x4d, 0x9f, 0x1e,
	0xcf, 0xb1, 0x28, 0xd5, 0xc2, 0x52, 0x82, 0x7f, 0x3d, 0x38, 0xa2, 0x98, 0xe5, 0x52, 0xa1, 0xf8,
	0x69, 0x16, 0xe7, 0xec, 0x26, 0x66, 0x71, 0x86, 0x82, 0xe2, 0x9f, 0x4f, 0x28, 0x15, 0xb9, 0x84,
	0xdd, 0x44, 0xc3, 0x51, 0x61, 0xf1, 0x28, 0x4f, 0x7b, 0xde, 0xc0, 0x1b, 0xfa, 0xa3, 0xdd, 0x50,
	0xef, 0x1e, 0x4e, 0x98, 0x54, 0x31, 0x4b, 0x70, 0x92, 0xd2, 0x4f, 0xc9, 0xca, 0x06, 0x93, 0x94,
	0x1c, 0x42, 0xdb, 0xae, 0xcd, 0xd3, 0x5e, 0x63, 0xe0, 0x0d, 0x3b, 0xb4, 0x65, 0xe2, 0x49, 0x4a,
	0x4e, 0xc0, 0x9f, 0xeb, 0x33, 0x59, 0x54, 0x72, 0xa1, 0x7a, 0x5b, 0x03, 0x6f, 0xd8, 0xa4, 0x60,
	0xa1, 0x5b, 0x2e, 0x14, 0x39, 0x06, 0x90, 0x28, 0x65, 0xce, 0xcd, 0xea, 0xed, 0x81, 0x37, 0xec,
	0xd2, 0x8e, 0x43, 0x26, 0x69, 0xf0, 0x8f, 0x07, 0x5f, 0xbe, 0x2d, 0x5b, 0x96, 0x9c, 0x49, 0x24,
	0xa7, 0xd0, 0x9c, 0x63, 0x2c, 0xd1, 0x89, 0xf5, 0xad, 0xd8, 0x5f, 0x34, 0x44, 0x6d, 0x86, 0x8c,
	0xa0, 0x2b, 0x50, 0x3e, 0x15, 0x18, 0xc5, 0x8f, 0x0a, 0x85, 0x91, 0xe8, 0x8f, 0x3e, 0xb3, 0xcc,
	0xab, 0x39, 0x4f, 0xfe, 0xb8, 0x2b, 0x31, 0xa1, 0xbe, 0x25, 0xfd, 0xa8, 0x39, 0xe4, 0x3b, 0x68,
	0x17, 0x9c, 0xe5, 0x8a, 0x0b, 0x69, 0x44, 0xd7, 0x36, 0xdc, 0x58, 0xf4, 0x0e, 0x15, 0xad, 0x19,
	0x01, 0x87, 0xe3, 0x7b, 0x26, 0x36, 0xb8, 0xbb, 0xea, 0x90, 0xb7, 0xee, 0xd0, 0x21, 0xb4, 0x8d,
	0xcc, 0xca, 0xbc, 0x2e, 0x6d, 0x99, 0x78, 0x92, 0x92, 0x1e, 0xb4, 0x0a, 0x94, 0x32, 0xce, 0xd0,
	0x68, 0xe8, 0xd0, 0x2a, 0x0c, 0xbe, 0x07, 0x58, 0xd6, 0x83, 0x7c, 0x82, 0x86, 0xdb, 0xb7, 0x4b,
	0x1b, 0x79, 0x4a, 0xfa, 0xd0, 0xce, 0x5d, 0xd6, 0x6c, 0xf9, 0x91, 0xd6, 0x71, 0x70, 0x0d, 0x9d,
	0xfa, 0xca, 0x84, 0xc0, 0xf6, 0x2c, 0x96, 0x33, 0xb7, 0xd4, 0x7c, 0x93, 0xaf, 0x61, 0x67, 0x86,
	0x79, 0x36, 0x53, 0xce, 0xa7, 0xae, 0xf3, 0x29, 0xcf, 0x26, 0x4c, 0x51, 0x97, 0x0b, 0x7e, 0x03,
	0x58, 0x3a, 0x41, 0xbe, 0x59, 0x71, 0xcb, 0x1b, 0x6c, 0x0d, 0xfd, 0xd1, 0xc7, 0x35, 0xb7, 0x96,
	0x56, 0xe9, 0x3b, 0x3d, 0xa3, 0xd0, 0xd5, 0x75, 0xd2, 0xaa, 0x30, 0xb8, 0x80, 0x96, 0xa3, 0xbf,
	0xba, 0x90, 0x36, 0xc2, 0xa6, 0x2a, 0x8b, 0x5c, 0x18, 0x84, 0xb0, 0x47, 0x91, 0xe1, 0x5f, 0xb6,
	0xe0, 0x4b, 0xb7, 0x6b, 0x4b, 0xbd, 0x35, 0x4b, 0x83, 0x9f, 0xa1, 0x69, 0xa8, 0xaf, 0x8e, 0xf8,
	0x16, 0xf6, 0x04, 0x16, 0x71, 0xce, 0x72, 0x96, 0x45, 0x12, 0x13, 0xce, 0x52, 0xe9, 0x14, 0xee,
	0xd6, 0x89, 0x3b, 0x8b, 0x07, 0x7f, 0x37, 0xa0, 0x47, 0x51, 0x77, 0xb4, 0xf1, 0xf2, 0xfa, 0x19,
	0x99, 0x92, 0xd5, 0xe9, 0x63, 0xe8, 0x94, 0x02, 0x1f, 0xe7, 0xc6, 0x43, 0xdb, 0x95, 0x43, 0xeb,
	0xc6, 0x7b, 0x4b, 0xc2, 0xdb, 0x8a, 0x3f, 0xfe, 0x40, 0x97, 0x8b, 0xc9, 0x19, 0x34, 0xa7, 0x9a,
	0xec, 0x2a, 0xe1, 0xaf, 0x74, 0xec, 0xf8, 0x03, 0xb5, 0x39, 0x4d, 0x42, 0xbd, 0x99, 0x6b, 0x53,
	0x47, 0x32, 0xfb, 0x6b, 0x92, 0xc9, 0xf5, 0x1f, 0xa0, 0x53, 0x9f, 0xb1, 0xc1, 0x1e, 0x12, 0xc2,
	0xe7, 0xce, 0xd9, 0x48, 0xa2, 0x8a, 0xd6, 0x2b, 0xb5, 0x57, 0xd4, 0x15, 0x7f, 0xb0, 0x89, 0x2b,
	0x80, 0x76, 0x21, 0xb3, 0x48, 0x2d, 0x4a, 0x0c, 0xa6, 0xd0, 0x34, 0xd2, 0xde, 0xec, 0xaa, 0x13,
	0xf0, 0xcb, 0x58, 0x20, 0x53, 0x91, 0x49, 0xd9, 0x2a, 0x82, 0x85, 0xc6, 0xeb, 0x6d, 0xb7, 0xb5,
	0xa1, 0xed, 0x2e, 0x61, 0xc7, 0x22, 0x64, 0x1f, 0x9a, 0xd3, 0x85, 0x42, 0xe9, 0x4e, 0xb1, 0x81,
	0xee, 0x7c, 0x86, 0x59, 0xac, 0xf2, 0x67, 0xdb, 0xf9, 0x6d, 0x5a, 0xc7, 0xc1, 0x0f, 0xd0, 0x34,
	0xae, 0xe8, 0x91, 0x53, 0x5d, 0xb2, 0x76, 0xa0, 0xe3, 0x10, 0xfb, 0xea, 0xca, 0x78, 0x31, 0xe7,
	0x71, 0xfd, 0x1e, 0x5d, 0x38, 0xfa, 0xaf, 0x01, 0xdd, 0x5f, 0x57, 0xa6, 0x2f, 0xf9, 0x1d, 0xf6,
	0xdf, 0x1a, 0x4e, 0xe4, 0xb4, 0xaa, 0xf7, 0xbb, 0x13, 0xa1, 0x1f, 0x6c, 0xa2, 0xb8, 0xd9, 0x76,
	0x0f, 0x07, 0x66, 0xac, 0xc8, 0xfc, 0xe5, 0x01, 0x67, 0x76, 0xf5, 0xc6, 0xa1, 0xd3, 0x3f, 0x08,
	0xed, 0x0f, 0x21, 0xac, 0x7e, 0x08, 0xe1, 0xb5, 0xfe, 0x21, 0x90, 0x11, 0xc0, 0xf2, 0xcd, 0x90,
	0x2f, 0x2a, 0x21, 0x2f, 0x5e, 0x51, 0x7f, 0x75, 0x94, 0x92, 0x1b, 0xfd, 0xce, 0x5e, 0x74, 0x2f,
	0xf9, 0x6a, 0x73, 0x5b, 0xbf, 0x27, 0x60, 0xe8, 0x4d, 0x77, 0x0c, 0x72, 0xf1, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb0, 0x17, 0x09, 0xe1, 0xcd, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrchestratorClient interface {
	// RegisterChainManager is invoked by ChainManagers to register themselves with this Orchestrator.
	RegisterChainManager(ctx context.Context, in *RegisterChainManagerRequest, opts ...grpc.CallOption) (*RegisterChainManagerResponse, error)
	// UnregisterChainManager is invoked by ChainManager to gracefully unregister themselves with this Orchestrator.
	// This usually happens when problems are noticed on its connector and ChainManager needs to terminate itself.
	UnregsiterChainManager(ctx context.Context, in *UnregisterChainManagerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// RenewLease renews the lease between a ChainManager and this Orchestrator.
	// Upon lease expiration, Orchestrator will consider the ChainManager dead and be free to accept new registrations.
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*Lease, error)
	// ReportBlockEvents reports a new block on the monitored chain, as well as all fired events from this block.
	// The request stream must begin with a valid Preflight, followed by a Block, followed by zero or more Events.
	ReportBlockEvents(ctx context.Context, opts ...grpc.CallOption) (Orchestrator_ReportBlockEventsClient, error)
}

type orchestratorClient struct {
	cc *grpc.ClientConn
}

func NewOrchestratorClient(cc *grpc.ClientConn) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) RegisterChainManager(ctx context.Context, in *RegisterChainManagerRequest, opts ...grpc.CallOption) (*RegisterChainManagerResponse, error) {
	out := new(RegisterChainManagerResponse)
	err := c.cc.Invoke(ctx, "/grpc.Orchestrator/RegisterChainManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) UnregsiterChainManager(ctx context.Context, in *UnregisterChainManagerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.Orchestrator/UnregsiterChainManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*Lease, error) {
	out := new(Lease)
	err := c.cc.Invoke(ctx, "/grpc.Orchestrator/RenewLease", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ReportBlockEvents(ctx context.Context, opts ...grpc.CallOption) (Orchestrator_ReportBlockEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Orchestrator_serviceDesc.Streams[0], "/grpc.Orchestrator/ReportBlockEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorReportBlockEventsClient{stream}
	return x, nil
}

type Orchestrator_ReportBlockEventsClient interface {
	Send(*ReportBlockEventsRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type orchestratorReportBlockEventsClient struct {
	grpc.ClientStream
}

func (x *orchestratorReportBlockEventsClient) Send(m *ReportBlockEventsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orchestratorReportBlockEventsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorServer is the server API for Orchestrator service.
type OrchestratorServer interface {
	// RegisterChainManager is invoked by ChainManagers to register themselves with this Orchestrator.
	RegisterChainManager(context.Context, *RegisterChainManagerRequest) (*RegisterChainManagerResponse, error)
	// UnregisterChainManager is invoked by ChainManager to gracefully unregister themselves with this Orchestrator.
	// This usually happens when problems are noticed on its connector and ChainManager needs to terminate itself.
	UnregsiterChainManager(context.Context, *UnregisterChainManagerRequest) (*empty.Empty, error)
	// RenewLease renews the lease between a ChainManager and this Orchestrator.
	// Upon lease expiration, Orchestrator will consider the ChainManager dead and be free to accept new registrations.
	RenewLease(context.Context, *RenewLeaseRequest) (*Lease, error)
	// ReportBlockEvents reports a new block on the monitored chain, as well as all fired events from this block.
	// The request stream must begin with a valid Preflight, followed by a Block, followed by zero or more Events.
	ReportBlockEvents(Orchestrator_ReportBlockEventsServer) error
}

func RegisterOrchestratorServer(s *grpc.Server, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

func _Orchestrator_RegisterChainManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChainManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).RegisterChainManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Orchestrator/RegisterChainManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).RegisterChainManager(ctx, req.(*RegisterChainManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_UnregsiterChainManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterChainManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).UnregsiterChainManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Orchestrator/UnregsiterChainManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).UnregsiterChainManager(ctx, req.(*UnregisterChainManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Orchestrator/RenewLease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ReportBlockEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorServer).ReportBlockEvents(&orchestratorReportBlockEventsServer{stream})
}

type Orchestrator_ReportBlockEventsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*ReportBlockEventsRequest, error)
	grpc.ServerStream
}

type orchestratorReportBlockEventsServer struct {
	grpc.ServerStream
}

func (x *orchestratorReportBlockEventsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orchestratorReportBlockEventsServer) Recv() (*ReportBlockEventsRequest, error) {
	m := new(ReportBlockEventsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChainManager",
			Handler:    _Orchestrator_RegisterChainManager_Handler,
		},
		{
			MethodName: "UnregsiterChainManager",
			Handler:    _Orchestrator_UnregsiterChainManager_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _Orchestrator_RenewLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportBlockEvents",
			Handler:       _Orchestrator_ReportBlockEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "orchestrator.proto",
}
