// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/workflow.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protos "github.com/megaspacelab/megaconnect/protos"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployWorkflowRequest struct {
	// payload is the binary representation of the workflow
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployWorkflowRequest) Reset()         { *m = DeployWorkflowRequest{} }
func (m *DeployWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*DeployWorkflowRequest) ProtoMessage()    {}
func (*DeployWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ccbacdbbcab2ebd, []int{0}
}

func (m *DeployWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployWorkflowRequest.Unmarshal(m, b)
}
func (m *DeployWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *DeployWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployWorkflowRequest.Merge(m, src)
}
func (m *DeployWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_DeployWorkflowRequest.Size(m)
}
func (m *DeployWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployWorkflowRequest proto.InternalMessageInfo

func (m *DeployWorkflowRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UndeployWorkflowRequest struct {
	// workflow_id is the ID of workflow that needs to be undeployed
	WorkflowId           []byte   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UndeployWorkflowRequest) Reset()         { *m = UndeployWorkflowRequest{} }
func (m *UndeployWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*UndeployWorkflowRequest) ProtoMessage()    {}
func (*UndeployWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ccbacdbbcab2ebd, []int{1}
}

func (m *UndeployWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndeployWorkflowRequest.Unmarshal(m, b)
}
func (m *UndeployWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndeployWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *UndeployWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndeployWorkflowRequest.Merge(m, src)
}
func (m *UndeployWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_UndeployWorkflowRequest.Size(m)
}
func (m *UndeployWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UndeployWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UndeployWorkflowRequest proto.InternalMessageInfo

func (m *UndeployWorkflowRequest) GetWorkflowId() []byte {
	if m != nil {
		return m.WorkflowId
	}
	return nil
}

type DeployWorkflowResponse struct {
	// workflow_id is the ID of the deployed workflow
	WorkflowId           []byte   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployWorkflowResponse) Reset()         { *m = DeployWorkflowResponse{} }
func (m *DeployWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*DeployWorkflowResponse) ProtoMessage()    {}
func (*DeployWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ccbacdbbcab2ebd, []int{2}
}

func (m *DeployWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployWorkflowResponse.Unmarshal(m, b)
}
func (m *DeployWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployWorkflowResponse.Marshal(b, m, deterministic)
}
func (m *DeployWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployWorkflowResponse.Merge(m, src)
}
func (m *DeployWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_DeployWorkflowResponse.Size(m)
}
func (m *DeployWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployWorkflowResponse proto.InternalMessageInfo

func (m *DeployWorkflowResponse) GetWorkflowId() []byte {
	if m != nil {
		return m.WorkflowId
	}
	return nil
}

type GetMBlockRequest struct {
	// height is the height of the MBlock
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMBlockRequest) Reset()         { *m = GetMBlockRequest{} }
func (m *GetMBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetMBlockRequest) ProtoMessage()    {}
func (*GetMBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ccbacdbbcab2ebd, []int{3}
}

func (m *GetMBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMBlockRequest.Unmarshal(m, b)
}
func (m *GetMBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetMBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMBlockRequest.Merge(m, src)
}
func (m *GetMBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetMBlockRequest.Size(m)
}
func (m *GetMBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMBlockRequest proto.InternalMessageInfo

func (m *GetMBlockRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*DeployWorkflowRequest)(nil), "grpc.DeployWorkflowRequest")
	proto.RegisterType((*UndeployWorkflowRequest)(nil), "grpc.UndeployWorkflowRequest")
	proto.RegisterType((*DeployWorkflowResponse)(nil), "grpc.DeployWorkflowResponse")
	proto.RegisterType((*GetMBlockRequest)(nil), "grpc.GetMBlockRequest")
}

func init() { proto.RegisterFile("grpc/workflow.proto", fileDescriptor_3ccbacdbbcab2ebd) }

var fileDescriptor_3ccbacdbbcab2ebd = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0xa5, 0x3f, 0x4a, 0x7f, 0x30, 0x4a, 0x5b, 0x53, 0xac, 0x65, 0xab, 0x28, 0x3d, 0x95, 0x1e,
	0xb2, 0xfe, 0x39, 0x69, 0x6f, 0x45, 0xd1, 0x22, 0xbd, 0x54, 0x44, 0xf0, 0x22, 0x49, 0x9a, 0xa6,
	0x4b, 0x77, 0x37, 0x71, 0x93, 0xa5, 0xec, 0xe7, 0xf1, 0x8b, 0x4a, 0x36, 0x8d, 0xe0, 0xd2, 0xe2,
	0xf1, 0xcd, 0xcc, 0x9b, 0x37, 0xef, 0x0d, 0x74, 0x44, 0xa6, 0x58, 0xb8, 0x91, 0xd9, 0x7a, 0x19,
	0xcb, 0x0d, 0x56, 0x99, 0x34, 0x12, 0xd5, 0x6d, 0x31, 0xe8, 0x94, 0x40, 0x87, 0x09, 0x8d, 0x25,
	0x5b, 0xbb, 0x56, 0xd0, 0x17, 0x52, 0x8a, 0x98, 0x87, 0x25, 0xa2, 0xf9, 0x32, 0xe4, 0x89, 0x32,
	0x85, 0x6b, 0x0e, 0xae, 0xe0, 0xf8, 0x9e, 0xab, 0x58, 0x16, 0x6f, 0xdb, 0x7d, 0x73, 0xfe, 0x99,
	0x73, 0x6d, 0x50, 0x0f, 0xfe, 0x2b, 0x52, 0xc4, 0x92, 0x2c, 0x7a, 0xb5, 0x8b, 0xda, 0xf0, 0x70,
	0xee, 0xe1, 0xe0, 0x0e, 0x4e, 0x5e, 0xd3, 0xc5, 0x4e, 0xd2, 0x39, 0x1c, 0xf8, 0xbb, 0x3e, 0x22,
	0x4f, 0x04, 0x5f, 0x9a, 0x2e, 0x06, 0xb7, 0xd0, 0xad, 0xca, 0x69, 0x25, 0x53, 0xcd, 0xff, 0xa6,
	0x8e, 0xa0, 0xfd, 0xc8, 0xcd, 0x6c, 0x62, 0x9d, 0x79, 0xbd, 0x2e, 0x34, 0x56, 0x3c, 0x12, 0x2b,
	0x53, 0xce, 0xd7, 0xe7, 0x5b, 0x74, 0xfd, 0xf5, 0x0f, 0x5a, 0x5e, 0x61, 0x46, 0x52, 0x22, 0x78,
	0x86, 0x9e, 0xa1, 0xf9, 0x5b, 0x1a, 0xf5, 0xb1, 0x0d, 0x0d, 0xef, 0xf4, 0x1f, 0x9c, 0xee, 0x6e,
	0x6e, 0xaf, 0x9d, 0x42, 0xbb, 0x9a, 0x01, 0x3a, 0x73, 0x8c, 0x3d, 0xd9, 0x04, 0x5d, 0xec, 0xfe,
	0x80, 0xfd, 0x1f, 0xf0, 0x83, 0xfd, 0x03, 0x1a, 0x43, 0xeb, 0x25, 0xa7, 0x9a, 0x65, 0x11, 0xe5,
	0xce, 0x1d, 0xda, 0x33, 0x1a, 0x34, 0x5d, 0x41, 0x63, 0x37, 0x77, 0x59, 0x43, 0x63, 0x38, 0xfa,
	0x09, 0x65, 0x52, 0x3c, 0x95, 0xee, 0x2d, 0xdd, 0x1e, 0x52, 0x4d, 0xab, 0x4a, 0x9f, 0x8c, 0xde,
	0x87, 0x22, 0x32, 0xab, 0x9c, 0x62, 0x26, 0x93, 0x30, 0xe1, 0x82, 0x68, 0x45, 0x18, 0x8f, 0x09,
	0x2d, 0x01, 0x93, 0x69, 0xca, 0x99, 0x09, 0xed, 0x32, 0xda, 0x28, 0xa9, 0x37, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x31, 0x8f, 0xff, 0x53, 0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkflowManagerClient is the client API for WorkflowManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkflowManagerClient interface {
	// DeployWorkflow deploys a workflow to the network.
	DeployWorkflow(ctx context.Context, in *DeployWorkflowRequest, opts ...grpc.CallOption) (*DeployWorkflowResponse, error)
	// UndeployWorkflow undeploys a workflow from the network.
	UndeployWorkflow(ctx context.Context, in *UndeployWorkflowRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// SubscribeMBlock will subscribe to new blocks from megaspace network.
	SubscribeMBlock(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (WorkflowManager_SubscribeMBlockClient, error)
	// GetMBlockByHeight will get the block by height.
	GetMBlockByHeight(ctx context.Context, in *GetMBlockRequest, opts ...grpc.CallOption) (*protos.MBlock, error)
}

type workflowManagerClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowManagerClient(cc *grpc.ClientConn) WorkflowManagerClient {
	return &workflowManagerClient{cc}
}

func (c *workflowManagerClient) DeployWorkflow(ctx context.Context, in *DeployWorkflowRequest, opts ...grpc.CallOption) (*DeployWorkflowResponse, error) {
	out := new(DeployWorkflowResponse)
	err := c.cc.Invoke(ctx, "/grpc.WorkflowManager/DeployWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) UndeployWorkflow(ctx context.Context, in *UndeployWorkflowRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.WorkflowManager/UndeployWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagerClient) SubscribeMBlock(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (WorkflowManager_SubscribeMBlockClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorkflowManager_serviceDesc.Streams[0], "/grpc.WorkflowManager/SubscribeMBlock", opts...)
	if err != nil {
		return nil, err
	}
	x := &workflowManagerSubscribeMBlockClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorkflowManager_SubscribeMBlockClient interface {
	Recv() (*protos.MBlock, error)
	grpc.ClientStream
}

type workflowManagerSubscribeMBlockClient struct {
	grpc.ClientStream
}

func (x *workflowManagerSubscribeMBlockClient) Recv() (*protos.MBlock, error) {
	m := new(protos.MBlock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workflowManagerClient) GetMBlockByHeight(ctx context.Context, in *GetMBlockRequest, opts ...grpc.CallOption) (*protos.MBlock, error) {
	out := new(protos.MBlock)
	err := c.cc.Invoke(ctx, "/grpc.WorkflowManager/GetMBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowManagerServer is the server API for WorkflowManager service.
type WorkflowManagerServer interface {
	// DeployWorkflow deploys a workflow to the network.
	DeployWorkflow(context.Context, *DeployWorkflowRequest) (*DeployWorkflowResponse, error)
	// UndeployWorkflow undeploys a workflow from the network.
	UndeployWorkflow(context.Context, *UndeployWorkflowRequest) (*empty.Empty, error)
	// SubscribeMBlock will subscribe to new blocks from megaspace network.
	SubscribeMBlock(*empty.Empty, WorkflowManager_SubscribeMBlockServer) error
	// GetMBlockByHeight will get the block by height.
	GetMBlockByHeight(context.Context, *GetMBlockRequest) (*protos.MBlock, error)
}

func RegisterWorkflowManagerServer(s *grpc.Server, srv WorkflowManagerServer) {
	s.RegisterService(&_WorkflowManager_serviceDesc, srv)
}

func _WorkflowManager_DeployWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).DeployWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WorkflowManager/DeployWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).DeployWorkflow(ctx, req.(*DeployWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_UndeployWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeployWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).UndeployWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WorkflowManager/UndeployWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).UndeployWorkflow(ctx, req.(*UndeployWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManager_SubscribeMBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowManagerServer).SubscribeMBlock(m, &workflowManagerSubscribeMBlockServer{stream})
}

type WorkflowManager_SubscribeMBlockServer interface {
	Send(*protos.MBlock) error
	grpc.ServerStream
}

type workflowManagerSubscribeMBlockServer struct {
	grpc.ServerStream
}

func (x *workflowManagerSubscribeMBlockServer) Send(m *protos.MBlock) error {
	return x.ServerStream.SendMsg(m)
}

func _WorkflowManager_GetMBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagerServer).GetMBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WorkflowManager/GetMBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagerServer).GetMBlockByHeight(ctx, req.(*GetMBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.WorkflowManager",
	HandlerType: (*WorkflowManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployWorkflow",
			Handler:    _WorkflowManager_DeployWorkflow_Handler,
		},
		{
			MethodName: "UndeployWorkflow",
			Handler:    _WorkflowManager_UndeployWorkflow_Handler,
		},
		{
			MethodName: "GetMBlockByHeight",
			Handler:    _WorkflowManager_GetMBlockByHeight_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMBlock",
			Handler:       _WorkflowManager_SubscribeMBlock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/workflow.proto",
}
