// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"fmt"
	"io/ioutil"
	"unicode/utf8"

	"github.com/megaspacelab/megaconnect/workflow/parser/goccgen/util"
	"github.com/megaspacelab/megaconnect/workflow/parser/goccgen/token"
)

const (
	NoState    = -1
	NumStates  = 68
	NumSymbols = 78
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	fmt.Printf("Lexer.Scan() pos=%d\n", l.pos)
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		fmt.Printf("\tpos=%d, line=%d, col=%d, state=%d\n", l.pos, l.line, l.column, state)
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		fmt.Printf("\tS%d, : tok=%s, rune == %s(%x), next state == %d\n", state, token.TokMap.Id(tok.Type), util.RuneToString(rune1), rune1, nextState)
		fmt.Printf("\t\tpos=%d, size=%d, start=%d, end=%d\n", l.pos, size, start, end)
		if nextState != -1 {
			fmt.Printf("\t\taction:%s\n", ActTab[nextState].String())
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	fmt.Printf("Token at %s: %s \"%s\"\n", tok.String(), token.TokMap.Id(tok.Type), tok.Lit)

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'm'
1: 'o'
2: 'n'
3: 'i'
4: 't'
5: 'o'
6: 'r'
7: 'e'
8: 'v'
9: 'e'
10: 'n'
11: 't'
12: 'a'
13: 'c'
14: 't'
15: 'i'
16: 'o'
17: 'n'
18: 'c'
19: 'h'
20: 'a'
21: 'i'
22: 'n'
23: 'c'
24: 'o'
25: 'n'
26: 'd'
27: 'i'
28: 't'
29: 'i'
30: 'o'
31: 'n'
32: 'v'
33: 'a'
34: 'r'
35: 't'
36: 'r'
37: 'u'
38: 'e'
39: 'f'
40: 'a'
41: 'l'
42: 's'
43: 'e'
44: '{'
45: '}'
46: '='
47: ':'
48: '|'
49: '|'
50: '&'
51: '&'
52: '='
53: '='
54: '!'
55: '='
56: '>'
57: '>'
58: '='
59: '<'
60: '<'
61: '='
62: '+'
63: '-'
64: '*'
65: '/'
66: '('
67: ')'
68: ' '
69: '\t'
70: '\r'
71: '\n'
72: '/'
73: '/'
74: '0'-'9'
75: 'a'-'z'
76: 'A'-'Z'
77: .
*/
